<?php
/*
* 
*
*
*
*/



	function tommys_webform_postcode_form_alter(&$form, &$form_state, $form_id) {
		if (strpos($form_id, 'webform_client_form_') === 0) {
			
				$form['name']  = array('#type' => 'textfield',
					'#title' => t('zipcode'),
						'#maxlength' => USERNAME_MAX_LENGTH,
							'#size' => 5,
							
							'#required' => TRUE,
							'#attributes' => array(
							'onblur' => 'clickrecall(this, "getLocation()")',
							'onclick' => 'clickclear(this, "getLocation()")'
								),
							'#value' => t(''),
							'#ajax' => array(
							'callback' => 'getLocation()',
							'wrapper' => 'participants',
						),
						
				);
					$form['add_participant'] = array(
					'#type' => 'button',
					'#value' => t('Get address'),
					'#href' => 'getLocation()',
					'#ajax' => array(
					'callback' => 'getLocation()',
					'wrapper' => 'participants',
						),
				);
				
				
				
				
				


		}
		
	}
	
	function ajax_pre_render_element_alter($element) {
		
		
		
		
		
		
		
	}
	
	
	
	
	