<?php
/*
* 
*
*
*
*/



	function tommys_webform_postcode_form_alter(&$form, &$form_state, $form_id) {
		if (strpos($form_id, 'webform_client_form_') === 0) {
				//echo'<pre>';
			   //var_dump($form_id);
			    // echo'<pre>';
						  $form['submitted']['node']['#autocomplete_path'] = 'node/autocomplete';
								$form['#attached']['js'] = array(
											drupal_get_path('tommys_webform_postcode', 'ajax_example') . '/map.js',
											);
								$form['name']  = array('#type' => 'textfield',
											'#title' => t('zipcode'),
											'#size' => 5,
											'#id'     =>'zipcode1',
											'#required' => TRUE,
											'#value'=>123,
											'#weight'=>1,
											'#method'=>'POST' ,
											'#action' => request_uri("https://maps.google.com/maps/api/js?sensor=false"),
											'#attributes' => array(
											'onblur' => '$post(this.value).clickrecall(this,value,"getLocation()")',
											'onclick' => 'clickclear(this, "jqsub")'
												),
											'#value' => t(''),
											'#ajax' => array(
											'callback' => 'jqsub()',
											'wrapper' => 'participants',
												),
						  
						
						
									);
								$form['add_participant'] = array(
															'#type' => 'button',
															'#value' => t('Get address'),
					'#href' => 'getLocation()',
						'#weight'=>2,
					'#ajax' => array(
					'callback' => 'getLocation()',
					'wrapper' => 'participants',
						),
				);
				$vars['scripts'] = drupal_get_js();
				
				
				
				
				
				
				
				  
				
        
				
				
				
				
				
				
				
				
				
				
				
				
				
				
				
				
				
				
				
				


		}
		
	}
	
	function ajax_pre_render_element_alter($element) {
		
		
		
		
		
		
		
	}
	
	
	
	
		function tommys_webform_postcode_webform_select_options_info() {
		
			$items = array();
			
		    echo'<pre>';
			var_dump($item);
			echo'<pre>';
			
		
		
		
		
		
		
		
		}
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	