<?php
/*
* 
*
*
*
*/
	function tommys_webform_postcode_field_info() {
	  return array(
		'tommys_webform_postcode' => array(
		  'label' => t('tommys_webform_postcode'),
		  'description' => t('enter your zip code here .'),
		  'default_widget' => 'tommys_webform_postcode',
		  'default_formatter' => 'tommys_webform_postcode_defaults',
		),
	  );
	 
	}
	function tommys_webform_postcode_field_settings_form($field, $instance, $has_data) {
		$settings = $field['settings'];
			// Add your global settings fields here
		$form = array();
	  return $form;
	}
	function tommys_webform_postcode_form_alter(&$form, &$form_state, $form_id,$items) {
			$forms = array();
		if ($form_id == 'webform_client_form_1'){
		
			
			$form['submitted']['node']['#autocomplete_path'] = 'node/autocomplete';
				$form['#attached']['js'] = array(
															drupal_get_path('tommys_webform_postcode', 'ajax_example') . 'js/map.js',
														);
														
		drupal_add_js('jQuery(document).ready(function () { 
			
			

			jQuery("#edit-submitted-postal-code").
hover(function(){
			alert("enterzip");
			
			});

		jQuery("#edit-submitted-address-line-1").
hover(function(){
			alert("edit-submitted-address-line-1");
			});
			



		jQuery("#edit-submitted-address-line-2").
hover(function(){
			alert("edit-submitted-address-line-2");
			});



		jQuery("#edit-submitted-address-line-3").
hover(function(){
			alert("edit-submitted-address-line-3");
			});
			jQuery("#edit-submitted-locality").
hover(function(){
			alert("locality");
			});
			jQuery("#edit-submitted-county").
hover(function(){
			alert("");
			});
			jQuery("#edit-submitted-province").
hover(function(){
			alert("province");
			});

	jQuery("#edit-submitted-country").
hover(function(){
			alert("enterzip");
			});






















		});', 'inline');										
								drupal_add_js('https://maps.google.com/maps/api/js?v=3', 'external');
											$form['zipcode']  = array('#type' => 'textfield',
											'#title' => t('zipcode'),
											'#size' => 5,
											'#name'=>'zip',
											'#id'     =>'zip',
											'#required' => TRUE,
											'#value' => '<input class="form-button" type="zip" value="" onblur="getLocation()" />',
											'#weight'=>1,
											'#method'=>'POST',
											
											'#action' => request_uri("js/map.js"),
											'#attributes' => array(
											'onblur' => '$post(this.value).clickrecall(this,value,"getLocation()")',
											'onclick' => 'getLocation()',
											'onhover'=>'jqsub()',
											  
												),
												
											'#value' => t(''),
											'#ajax' => array(
											'callback' => 'jqsub',
											'wrapper' => 'participants',
												),
										);
								
					
							  $form['actions']['cancel'] = array(
								'#markup' => l(t('Cancel'), 'foo/bar'),
								'#weight'=> '-6',
		
							
	
	

  );
  
										
								
								
											//m($form);
        
				
				
				                  

				
				//upal_set_message("Form ID is : " . $form_id);
//upal_set_message(dprint_r($form, TRUE));
				
				
										echo'<pre>';
									//var_dump($form);	
										echo'</pre>';
				
				
				
			 
				
			


		}
		return $form;

		
		
	
		
	}
	
	
	
	
			function hook_webform_component_presave(&$component) {
				$component['extra']['new_option'] = 'foo';
			
			
			
			
				return $component;
			}
		
	
	
	
				function tommys_webform_postcode_field_widget_info() {
					$widgets = array();

  $widgets['addressfield_standard'] = array(
    'label' => t('Dynamic zip address form'),
    'field types' => array('tommys_webform_postcode'),
    'settings' => array(
      //'available_countries' => array(),
      // Can't use variable_get('site_default_country') here because it would
      // set the value in stone. Instead, the site_default option allows the
      // default country to always reflect the current site setting.
      //'default_country' => 'site_default',
      'format_handlers' => array('zip'),
    ),
  );

  return $widgets;
}
	
	
	function getLocation() {
    drupal_add_js('http://maps.googleapis.com/maps/api/js?sensor=false', 'external');
    drupal_add_js(drupal_get_path('tommys_webform_postcode', 'simple_gmap') . '/map.js');
}
	
	
	
	
/**
 * Implements hook_field_widget_form().
 */
/*
function rgb_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {

  if ($field['cardinality'] == 1) {
    $element['#type'] = 'fieldset';
  }

  $element['rgb'] = array(
    '#type' => 'textfield',
    '#field_prefix' => t('RGB: #'),
    '#size' => 6,
    '#default_value' => isset($items[$delta]['rgb']) ? $items[$delta]['rgb'] : '',
  );

  $element['label'] = array(
    '#type' => 'textfield',
    '#field_prefix' => t('Color name: '),
    '#default_value' => isset($items[$delta]['label']) ? $items[$delta]['label'] : '',
  );

  return $element;
}
*/
	
	
	